name: Update Provider

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests PyYAML
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Fetch Provider
      run: |
        python cloudflare.py
        wget -O reject.txt https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
        wget -O private.txt https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
        wget -O gfw.txt https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
        wget -O tld-not-cn.txt https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
        wget -O telegramcidr.txt https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
        wget -O applications.txt https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
        date +%s > timestamp
    - name: Commit and push changes
      run: |
        git config --global user.name "Action"
        git config --global user.email "action@github.com"
        git add .
        git commit -m "Sync"
        git push
